#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$HERE")"
ZONES="$PKG/zones"
SRC="$ZONES/src"
KEYS="$ZONES/signed/keys"
OUT_ROOT="$ZONES/signed/root"
OUT_AUTH="$ZONES/signed/auth"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

INCEPTION=20260101000000
EXPIRY=20400101000000

CHILDREN=(secure.test bogus-zone.test wildcard-signed.test)

mkdir -p "$KEYS" "$OUT_ROOT" "$OUT_AUTH"

BIND_IMAGE=internetsystemsconsortium/bind9:9.20

if [[ "${PROPGATE_SIGN_LOCAL:-}" != "1" ]] && command -v docker >/dev/null 2>&1; then
  echo "signing via $BIND_IMAGE"
  bind_tool() {
    docker run --rm -u "$(id -u):$(id -g)" \
      -v "$PKG:$PKG" -v "$WORK:$WORK" -w "$1" \
      --entrypoint "$2" "$BIND_IMAGE" "${@:3}"
  }
elif command -v dnssec-signzone >/dev/null 2>&1; then
  echo "signing with local BIND tools ($(dnssec-signzone -h 2>&1 | head -1 || true))"
  echo "  note: commit output produced by $BIND_IMAGE where possible" >&2
  bind_tool() {
    local dir="$1" cmd="$2"
    shift 2
    (cd "$dir" && "$cmd" "$@")
  }
else
  echo "error: need Docker or local BIND tools (dnssec-signzone)" >&2
  exit 1
fi

keygen() { bind_tool "$KEYS" dnssec-keygen "$@"; }
signzone() { bind_tool "$WORK" dnssec-signzone "$@"; }

key_prefix_for() {
  if [[ "$1" == "." ]]; then
    printf 'K.+'
  else
    printf 'K%s.+' "$1"
  fi
}

ensure_keys() {
  local zone="$1" algo="$2" ksk_bits="$3" zsk_bits="$4"
  local prefix
  prefix="$(key_prefix_for "$zone")"

  if compgen -G "$KEYS/$prefix*.key" >/dev/null; then
    return
  fi

  echo "  generating keys for $zone ($algo)"
  if [[ -n "$ksk_bits" ]]; then
    keygen -a "$algo" -b "$ksk_bits" -f KSK -n ZONE "$zone" >/dev/null
    keygen -a "$algo" -b "$zsk_bits" -n ZONE "$zone" >/dev/null
  else
    keygen -a "$algo" -f KSK -n ZONE "$zone" >/dev/null
    keygen -a "$algo" -n ZONE "$zone" >/dev/null
  fi
}

sign_one() {
  local zone="$1" origin="$2" output="$3"

  cp "$SRC/$zone.zone" "$WORK/$zone.zone"
  signzone -S -o "$origin" -K "$KEYS" -N keep \
    -s "$INCEPTION" -e "$EXPIRY" -P \
    -f "$output" -d "$WORK" "$WORK/$zone.zone" >/dev/null

  grep -v -e '^; File written on ' -e '^; dnssec_signzone version ' \
    "$output" > "$output.tmp"
  mv "$output.tmp" "$output"
}

inject_ds() {
  local target="$1" dsfile="$2"

  awk -v dsfile="$dsfile" '
    /^; BEGIN GENERATED DS$/ {
      print
      while ((getline line < dsfile) > 0) {
        print line
      }
      close(dsfile)
      skip = 1
      next
    }
    /^; END GENERATED DS$/ { skip = 0 }
    !skip { print }
  ' "$target" > "$target.tmp"

  mv "$target.tmp" "$target"
}

echo "signing children of test."
: > "$WORK/child-ds"

for zone in "${CHILDREN[@]}"; do
  if [[ "$zone" == "wildcard-signed.test" ]]; then
    ensure_keys "$zone" ECDSAP256SHA256 "" ""
  else
    ensure_keys "$zone" RSASHA256 2048 1024
  fi

  sign_one "$zone" "$zone" "$OUT_AUTH/$zone.zone.signed"

  cat "$WORK/dsset-$zone." >> "$WORK/child-ds"
  echo "  $zone"
done

inject_ds "$SRC/test.zone" "$WORK/child-ds"

echo "signing test."
ensure_keys test RSASHA256 2048 1024
sign_one test test "$OUT_ROOT/test.zone.signed"

inject_ds "$SRC/root.zone" "$WORK/dsset-test."

echo "signing the root"
ensure_keys . RSASHA256 2048 1024
sign_one root . "$OUT_ROOT/root.zone.signed"

echo "writing root.anchor"
{
  echo "; propgate fixture root trust anchor. Regenerated by scripts/sign.sh."
  echo "; This signs a fake root under RFC 6761 .test — it protects nothing."
  grep -h 'DNSKEY.*257' "$KEYS"/K.+*.key | grep -v '^;'
} > "$ZONES/signed/root.anchor"

echo "corrupting bogus-zone.test"
node "$HERE/corrupt-rrsig.mjs" "$OUT_AUTH/bogus-zone.test.zone.signed" DNSKEY

node "$HERE/revision.mjs" --write >/dev/null
echo "revision: $(cat "$PKG/REVISION")"
echo "done"
